### ISSUE TITLE
9.9.2-16183修补报错

### ISSUE THREAD

**Issue by shi-an** [xh321/LiteLoaderQQNT-PatcherNFixer#2]
![image](https://github.com/xh321/LiteLoaderQQNT-PatcherNFixer/assets/79352488/bb538953-df6f-41ed-a235-1c545807ce68)

**Comment by xh321** [comment]
可能是你卸载qq时有残留，注册表里面的路径不正确。建议完整卸载并重新安装一次qq

**Comment by shi-an** [comment]
> 可能是你卸载qq时有残留，注册表里面的路径不正确。建议完整卸载并重新安装一次qq

![{534640B4-33DB-4c0d-A814-2A71ED7291C5}](https://github.com/xh321/LiteLoaderQQNT-PatcherNFixer/assets/79352488/d6b197df-4cff-43e9-b21d-ded5de26b7ef)
