### ISSUE TITLE
安装多个QQ无法修改路径

### ISSUE THREAD

**Issue by 2436238575** [xh321/LiteLoaderQQNT-PatcherNFixer#3]
![屏幕截图 2023-11-04 191843](https://github.com/xh321/LiteLoaderQQNT-PatcherNFixer/assets/112002249/9add1b11-eb9c-45e9-b1d3-d8345fe4c054)

**Comment by xh321** [comment]
竟然有安装多个QQ的需求，没考虑到，我下一个版本加一个手动选择路径的功能吧

**Comment by xh321** [comment]
已适配
