### ISSUE TITLE
提示未能找到launcher.json

### ISSUE THREAD

**Issue by Sikz1218** [xh321/LiteLoaderQQNT-PatcherNFixer#5]
QQ9.8.5,使用安装脚本-全自动patch程序安装,提示未能找到launcher.json,我去看了看QQ安装目录确实没有,重装了这个版本的QQ也还是没有这个文件.

![屏幕截图_20240101_192134](https://github.com/xh321/LiteLoaderQQNT-PatcherNFixer/assets/69615623/61e21b7a-41bc-4dfd-919b-7a283c8a8b53)

**Comment by xh321** [comment]
新版本QQ未适配，请等待框架后续更新

**Comment by Sikz1218** [comment]
> 新版本QQ未适配，请等待框架后续更新

疑惑, 9.8.5不是应该支持的嘛?全程按照安装方法操作的.
![屏幕截图_20240101_200807](https://github.com/xh321/LiteLoaderQQNT-PatcherNFixer/assets/69615623/6349cc3a-1704-407b-a453-f6b0f21b32ab)

**Comment by xh321** [comment]
> > 新版本QQ未适配，请等待框架后续更新
> 
> 疑惑, 9.8.5不是应该支持的嘛?全程按照安装方法操作的. ![屏幕截图_20240101_200807](https://private-user-images.githubusercontent.com/69615623/293584780-6349cc3a-1704-407b-a453-f6b0f21b32ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMzQ5MjYsIm5iZiI6MTcwNDEzNDYyNiwicGF0aCI6Ii82OTYxNTYyMy8yOTM1ODQ3ODAtNjM0OWNjM2EtMTcwNC00MDdiLWE0NTMtZjZiMGYyMWIzMmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDE4NDM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMDI4NGNmNzIyOTBmZDg1MWQxMjFjMDQzMTQwMjk1YmNkZWM0N2I0ZDhmYmQzZDMzMGQ5YmIxNTFjMjFjYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wtQKY9aX4LhPYDe0O5sCVXgTTsSgC07gHbC9MZwyZA0)

哦，这个是没说清楚，小版本和大版本是绑定的，16183完整名称是9.9.2-16183，所以高于9.9.2-16183的都不支持，包括9.9.5
