### ISSUE TITLE
关于适配更新的问题

### ISSUE THREAD

**Issue by RaTaiHok** [xh321/LiteLoaderQQNT-PatcherNFixer#6]
啊啊
992版本他现在已经不让我登了
请问什么时候可以做出996的适配呢

**Comment by xh321** [comment]
16183以以下是可以的

**Comment by RaTaiHok** [comment]
> 16183以以下是可以的

我知道是可以的但是是QQ登录问题（捂脸）![Screenshot_20240102_232155_com.microsoft.rdc.androidx.jpg](https://github.com/xh321/LiteLoaderQQNT-PatcherNFixer/assets/99812350/153ce0b4-a995-4a62-93e8-f40ff28063e7)

**Comment by xh321** [comment]
> > 16183以以下是可以的
> 
> 我知道是可以的但是是QQ登录问题（捂脸）![Screenshot_20240102_232155_com.microsoft.rdc.androidx.jpg](https://private-user-images.githubusercontent.com/99812350/293734414-153ce0b4-a995-4a62-93e8-f40ff28063e7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTIyNjAsIm5iZiI6MTcwNDIxMTk2MCwicGF0aCI6Ii85OTgxMjM1MC8yOTM3MzQ0MTQtMTUzY2UwYjQtYTk5NS00YTYyLTkzZTgtZjQwZmYyODA2M2U3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE2MTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MDRkNTEzNmMzNzk1YjFkMzlmMTVlYjg2YWExMzQ5YmJlMDQ1ZWJkOTJlOGRmOGM1Zjg3NmUyMTNkMmRkODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KED7uRgrIj4p_GN29ZZ9J-gQ_G695vrBcGYeKbsCwjs)

我一直是用16183版本，没问题呀，你现在用的是什么版本

**Comment by RaTaiHok** [comment]
> > > 16183以以下是可以的
> > 
> > 我知道是可以的但是是QQ登录问题（捂脸）![Screenshot_20240102_232155_com.microsoft.rdc.androidx.jpg](https://private-user-images.githubusercontent.com/99812350/293734414-153ce0b4-a995-4a62-93e8-f40ff28063e7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTIyNjAsIm5iZiI6MTcwNDIxMTk2MCwicGF0aCI6Ii85OTgxMjM1MC8yOTM3MzQ0MTQtMTUzY2UwYjQtYTk5NS00YTYyLTkzZTgtZjQwZmYyODA2M2U3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE2MTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MDRkNTEzNmMzNzk1YjFkMzlmMTVlYjg2YWExMzQ5YmJlMDQ1ZWJkOTJlOGRmOGM1Zjg3NmUyMTNkMmRkODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KED7uRgrIj4p_GN29ZZ9J-gQ_G695vrBcGYeKbsCwjs)
> 
> 我一直是用16183版本，没问题呀，你现在用的是什么版本

9.9.2 16183
应该是QQ协议的问题而不是LiteLoader的问题吧

**Comment by xh321** [comment]
> > > > 16183以以下是可以的
> > > 
> > > 
> > > 我知道是可以的但是是QQ登录问题（捂脸）![Screenshot_20240102_232155_com.microsoft.rdc.androidx.jpg](https://private-user-images.githubusercontent.com/99812350/293734414-153ce0b4-a995-4a62-93e8-f40ff28063e7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTIyNjAsIm5iZiI6MTcwNDIxMTk2MCwicGF0aCI6Ii85OTgxMjM1MC8yOTM3MzQ0MTQtMTUzY2UwYjQtYTk5NS00YTYyLTkzZTgtZjQwZmYyODA2M2U3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE2MTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MDRkNTEzNmMzNzk1YjFkMzlmMTVlYjg2YWExMzQ5YmJlMDQ1ZWJkOTJlOGRmOGM1Zjg3NmUyMTNkMmRkODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KED7uRgrIj4p_GN29ZZ9J-gQ_G695vrBcGYeKbsCwjs)
> > 
> > 
> > 我一直是用16183版本，没问题呀，你现在用的是什么版本
> 
> 9.9.2 16183 应该是QQ协议的问题而不是LiteLoader的问题吧

真怪啊，这肯定和框架无关

**Comment by RaTaiHok** [comment]
> > > > > 16183以以下是可以的
> > > > 
> > > > 
> > > > 我知道是可以的但是是QQ登录问题（捂脸）![Screenshot_20240102_232155_com.microsoft.rdc.androidx.jpg](https://private-user-images.githubusercontent.com/99812350/293734414-153ce0b4-a995-4a62-93e8-f40ff28063e7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTIyNjAsIm5iZiI6MTcwNDIxMTk2MCwicGF0aCI6Ii85OTgxMjM1MC8yOTM3MzQ0MTQtMTUzY2UwYjQtYTk5NS00YTYyLTkzZTgtZjQwZmYyODA2M2U3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE2MTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MDRkNTEzNmMzNzk1YjFkMzlmMTVlYjg2YWExMzQ5YmJlMDQ1ZWJkOTJlOGRmOGM1Zjg3NmUyMTNkMmRkODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KED7uRgrIj4p_GN29ZZ9J-gQ_G695vrBcGYeKbsCwjs)
> > > 
> > > 
> > > 我一直是用16183版本，没问题呀，你现在用的是什么版本
> > 
> > 9.9.2 16183 应该是QQ协议的问题而不是LiteLoader的问题吧
> 
> 真怪啊，这肯定和框架无关

所以希望能尽快适配992以上的版本吧（
虽然QQ正常可以更新但是用不了LL
