### ISSUE TITLE
9.9.3-17412 文件校验 patch 地址

### ISSUE THREAD

**Issue by YuHuanTin** [xh321/LiteLoaderQQNT-PatcherNFixer#7]
![image](https://github.com/xh321/LiteLoaderQQNT-PatcherNFixer/assets/51024916/87049311-c643-49cc-ac89-0b9d92136512)

虽然 patch 了校验之后但是并不能正常使用 LiteLoadQQNT

使用Patch过的QQ.exe和原本的``launcher.json``,``package.json``的时候能够正常运行

但是使用``./LiteLoadQQNT``修改``./app_launcher/index.js``后无法运行（运行了几秒会退出？）

暂时不知道是patch的问题还是LiteLoad的问题

**Comment by xh321** [comment]
新版本不光需要Patch，他在js层还会检测到js全局对象，所以还需要等我们继续研究。

**Comment by xh321** [comment]
新版本框架已经推出，新版修补器也有了，感谢你的支持
