### ISSUE TITLE
请问是否能提供QQarm版本的支持呢？(我的问题，可以正常使用)

### ISSUE THREAD

**Issue by Niji-Nozomi** [xh321/LiteLoaderQQNT-PatcherNFixer#8]
今天凌晨闲来无聊打开QQ官网，看到新增了arm版本的QQ
然后就是安装 修补 报错_(我的问题导致错误提交的，后面折腾一下是可以正常使用的，在这里说一下对不起>.<)_
似乎并不需要修补就可以正常使用_(因为没使用过issues 我也不知道怎么撤回这条消息 只好硬着头皮发出来了...)_

**Comment by xh321** [comment]
直接close就好啦
